### ISSUE TITLE
some queries to api are timeouted

### ISSUE THREAD

**Issue by piotr-gawron** [chembl/chembl_webservices_2#153] opened 2018-01-24 14:30 UTC
I just noticed that some queries started to be time outed. Here is an example:
https://www.ebi.ac.uk/chembl/api/data/target/CHEMBL1862

To be more specific. The error is about proxy error, but it happens after long time of waiting:
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /chembl/api/data/target/CHEMBL1862.

Reason: Error reading from remote server
```

**Comment by mnowotka** [comment] 2018-01-24 14:35
Thanks for reporting this, I can confirm that this problem exists and it looks that it only affects single targets. If you know about any other URLs (not single targets), please let me know. I will inform you when this issue is resolved.

**Comment by mnowotka** [comment] 2018-01-24 15:14
OK, it should be better now but I'm still investigating the cause.

**Comment by piotr-gawron** [comment] 2018-01-24 15:18
Great,

Thanks a lot for fast answer.

**Comment by mnowotka** [comment] 2018-01-25 09:40
There was a storage issue which affected servers, it's fixed now but don't hesistate to create another ticket if there are more problems with the API.

**Closed by mnowotka** 2018-01-25 09:40 UTC
Labels: bug
